services:
  youtube-uploader:
    build: .
    container_name: youtube-upload-panel
    ports:
      - "23334:3000"
    environment:
      - HOST=0.0.0.0 
    volumes:
      - /root/apps/bots/ytupdater/accounts_db.json:/app/accounts_db.json
      - /tmp/uploads:/tmp/uploads
    restart: unless-stopped